## From pdf Session 3: Assignment 1

### Task 1

#### Question 1

Write a function to compute 5/0 and use try/except to catch the exceptions.

In [26]:
def compute_division(divisor):
    try:
        ans = 5/divisor
        print(ans)
    except BaseException as e:
        print('Division failed with reason', end=' ')
        print(e)
    except :
        print('Division failed')


In [27]:
compute_division(5)

1.0


In [28]:
compute_division(3)

1.6666666666666667


In [29]:
compute_division(0)

Division failed with reason division by zero


#### Question 2

Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"]   
and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
   
Hint: Subject,Verb and Object should be declared in the program as shown below.  
subjects=["Americans ","Indians"]  
verbs=["play","watch"]  
objects=["Baseball","Cricket"]   
    
Output should come as below:   
    
Americans play Baseball.   
Americans play Cricket.   
Americans watch Baseball.   
Americans watch Cricket.   
Indians play Baseball.   
Indians play Cricket.   
Indians watch Baseball.   
Indians watch Cricket.   


In [30]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
    for v in verbs:
        for o in objects:
            print(s,v,o)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task 2

#### Question 1

Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument.    
Specifically, when increasing is False, the i-th output column is the input vector    
raised element-wise to the power of N - i - 1.   

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.   


#### Here, I am trying to understand the problem with an example

If input vector v = [3,4,5]  
N = 4   
Then expected output mattrix is    
[ [3^(4-0-1),3^(4-1-1),3^(4-2-1),3^(4-3-1)],   
  [4^(4-0-1),4^(4-1-1),4^(4-2-1),4^(4-3-1)],    
  [5^(4-0-1),5^(4-1-1),5^(4-2-1),5^(4-3-1)]  ]    
  
On simplifying
[  [ 27, 9, 3, 1],    
   [ 64,16, 4, 1],    
   [125,25, 5, 1]   ]
   

#### Here, I am trying smaller pieces of python code to get the output.

In [2]:
import numpy as np


In [5]:
N=4
power = [x for x in range(N-1,-1,-1)]
power

[3, 2, 1, 0]

In [6]:
inp_vector = [3,4,5]
output_list = [a**b for a in inp_vector for b in power]
output_list

[27, 9, 3, 1, 64, 16, 4, 1, 125, 25, 5, 1]

In [8]:
np.array(output_list).reshape(len(inp_vector), -1)

array([[ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

### Actual solution is below

In [18]:
import numpy as np

def alex_vander_matrix(inp_vector, N, increasing=False):
    if increasing == False:
        power = [x for x in range(N-1,-1,-1)]
        output_list = [a**b for a in inp_vector for b in power]
        alex_vander_matrix = np.array(output_list).reshape(len(inp_vector), -1)

        return alex_vander_matrix
    
    else:
        print('This function is not defined for increasing case')
        return None

In [19]:
alex_vander_matrix([2,3,5], 5)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [625, 125,  25,   5,   1]])

In [20]:
alex_vander_matrix([1,2,3,4], 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])